#! /usr/bin/env bash


if [ $# -lt 2 ]; then
    echo "${0} <image.wic.bz2> </dev/sdX>"
    exit 0
fi

bunzip2 -c "${1}" | sudo dd of="${2}" bs=1M status=progress iflag=fullblock oflag=direct conv=fsync
